package:
  name: sqlite
  version: "3.8.11.1"

source:
  fn: sqlite-autoconf-3081101.tar.gz
  url: https://www.sqlite.org/2015/sqlite-autoconf-3081101.tar.gz
  sha1: d0e22d7e361b6f50830a3cdeafe35311443f8f9a

test:
  commands:
    - sqlite3 --version

about:
  home: http://www.sqlite.org/
  license: Public-Domain (http://www.sqlite.org/copyright.html)
  #license_family: Public-Domain
  summary: implements a self-contained, zero-configuration, SQL database engine
