package:
  name: sqlite
  version: "3.11.1"

source:
  fn: sqlite-autoconf-3110100.tar.gz
  url: https://www.sqlite.org/2016/sqlite-autoconf-3110100.tar.gz
  sha1: c4b4dcd735a4daf5a2e2bb90f374484c8d4dad29

build:
  number: 99

test:
  commands:
    - sqlite3 --version

about:
  home: http://www.sqlite.org/
  license: Public-Domain (http://www.sqlite.org/copyright.html)
  #license_family: Public-Domain
  summary: implements a self-contained, zero-configuration, SQL database engine
