package:
  name: pycrypto
  version: "2.6.1"

source:
  fn: pycrypto-2.6.1.tar.gz
  url: https://pypi.python.org/packages/source/p/pycrypto/pycrypto-2.6.1.tar.gz
  md5: 55a61a054aa66812daf5161a0d5d7eda

build:
  number: 99

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - Crypto
    - Crypto.Cipher
    - Crypto.Hash
    - Crypto.Protocol
    - Crypto.PublicKey
    - Crypto.Random
    - Crypto.Random.Fortuna
    - Crypto.Random.OSRNG
    - Crypto.SelfTest
    - Crypto.SelfTest.Cipher
    - Crypto.SelfTest.Hash
    - Crypto.SelfTest.Protocol
    - Crypto.SelfTest.PublicKey
    - Crypto.SelfTest.Random
    - Crypto.SelfTest.Random.Fortuna
    - Crypto.SelfTest.Random.OSRNG
    - Crypto.SelfTest.Signature
    - Crypto.SelfTest.Util
    - Crypto.Signature
    - Crypto.Util

about:
  home: http://www.pycrypto.org/
  license: Public domain
  summary: 'Cryptographic modules for Python.'
