package:
  name: setuptools
  version: "20.2.2"

source:
  fn: setuptools-20.2.2.tar.gz
  url: https://pypi.python.org/packages/source/s/setuptools/setuptools-20.2.2.tar.gz
  md5: bf37191cb4c1472fb61e6f933d2006b1

build:
  preserve_egg_dir: True
  entry_points:
    - easy_install = setuptools.command.easy_install:main
    - easy_install-2.7 = setuptools.command.easy_install:main [py27]
  number: 99

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - pkg_resources
    - pkg_resources._vendor
    - pkg_resources._vendor.packaging
    - pkg_resources.extern
    - setuptools
    - setuptools.command
    - setuptools.extern
  commands:
    - easy_install --help
    - easy_install-2.7 --help [py27]

about:
  home: https://bitbucket.org/pypa/setuptools
  license: MIT License
  summary: 'Easily download, build, install, upgrade, and uninstall Python packages'
