package:
  name: conda
  version: "4.0.4"

source:
  git_url: https://github.com/conda/conda.git
  git_tag: 4.0.4

build:
  # These are present when the new environment is created
  # so we have to exempt them from the list of initial files
  # for conda-build to realize they should be included.
  always_include_files:
    - bin/conda  [unix]
    - bin/activate  [unix]
    - bin/deactivate  [unix]
  entry_points:
    - conda = conda.cli:main
  string: py{{ environ['CONDA_PY'] }}
  number: 0

requirements:
  build:
    - python
    - setuptools
    - requests
    - pyyaml
    - conda-env
    - pycosat
    - menuinst [win]
  run:
    - python
    - pycosat >=0.6.1
    - pyyaml
    - requests
    - conda-env
    - menuinst   [win]

test:
  commands:
    - conda --version
    - conda info
  imports:
    - conda


about:
  home: http://conda.pydata.org/
  license: BSD
  license_file: LICENSE.txt
  summary: OS-agnostic, system-level binary package manager. 
