package:
  name: markupsafe
  version: "0.23"

source:
  fn: MarkupSafe-0.23.tar.gz
  url: https://pypi.python.org/packages/source/M/MarkupSafe/MarkupSafe-0.23.tar.gz
  md5: f5ab3deee4c37cd6a922fb81e730da6e

build:
  number: 99

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - markupsafe

about:
  home: http://github.com/mitsuhiko/markupsafe
  license: BSD License
  summary: 'Implements a XML/HTML/XHTML Markup safe string for Python'
