package:
  name: conda-env
  version: "2.4.5"

source:
  git_url: https://github.com/conda/conda-env.git
  git_tag: v2.4.5

build:
  number: 99

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - conda_env
    - conda_env.cli
    - conda_env.installers
    - conda_env.specs
    - conda_env.utils
  requires:
    - conda

about:
  home: https://github.com/conda/conda-env
  license: BSD
  summary: 'tools for interacting with conda environments'
