package:
  name: conda-env
  version: "2.4.2"

source:
  fn: conda-env-2.4.2.tar.gz
  url: https://pypi.python.org/packages/source/c/conda-env/conda-env-2.4.2.tar.gz
  md5: ac9a7c2beeb363cfffe37df0e5fa2e09

build:
  number: 99

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - conda_env
    - conda_env.cli
    - conda_env.installers
    - conda_env.specs
    - conda_env.utils
  requires:
    - conda

about:
  home: https://github.com/conda/conda-env
  license: BSD
  summary: 'tools for interacting with conda environments'
