package:
  name: conda-env
  version: "2.4.2"

source:
  fn: conda-env-2.4.2.tar.gz
  url: https://pypi.python.org/packages/source/c/conda-env/conda-env-2.4.2.tar.gz
  md5: ac9a7c2beeb363cfffe37df0e5fa2e09
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - conda-env = conda-env:main
    #
    # Would create an entry point called conda-env that calls conda-env.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - conda_env
    - conda_env.cli
    - conda_env.installers
    - conda_env.specs
    - conda_env.utils

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/conda/conda-env
  license: BSD
  summary: 'tools for interacting with conda environments'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
