package:
  name: patchelf
  version: "0.8"

source:
  fn: patchelf-0.8.tar.gz
  url: http://nixos.org/releases/patchelf/patchelf-0.8/patchelf-0.8.tar.gz
  md5: 407b229e6a681ffb0e2cdd5915cb2d01

build:
  number: 99

about:
  home: https://nixos.org/patchelf.html
  license: GPL
  summary: a small utility to modify the dynamic linker and RPATH of ELF executables"
