package:
  name: wheel
  version: "0.29.0"

source:
  fn: wheel-0.29.0.tar.gz
  url: https://pypi.python.org/packages/source/w/wheel/wheel-0.29.0.tar.gz
  md5: 555a67e4507cedee23a0deb9651e452f

build:
  number: 99
  entry_points:
    - wheel=wheel.tool:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  imports:
    - wheel
    - wheel.signatures
    - wheel.test
    - wheel.tool

  commands:
    - wheel --help

about:
  home: https://bitbucket.org/pypa/wheel/
  license: MIT
  summary: 'A built-package format for Python.'
