package:
  name: jinja2
  version: "2.8"

source:
  fn: Jinja2-2.8.tar.gz
  url: https://pypi.python.org/packages/source/J/Jinja2/Jinja2-2.8.tar.gz
  md5: edb51693fe22c53cee5403775c71a99e
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - jinja2 = jinja2:main
    #
    # Would create an entry point called jinja2 that calls jinja2.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - markupsafe

  run:
    - python
    - setuptools
    - markupsafe

test:
  # Python imports
  imports:
    - jinja2

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://jinja.pocoo.org/
  license: BSD License
  summary: 'A small but fast and easy to use stand-alone template engine written in pure python.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
