package:
  name: jinja2
  version: "2.8"

source:
  fn: Jinja2-2.8.tar.gz
  url: https://pypi.python.org/packages/source/J/Jinja2/Jinja2-2.8.tar.gz
  md5: edb51693fe22c53cee5403775c71a99e

build:
  number: 99

requirements:
  build:
    - python
    - setuptools
    - markupsafe

  run:
    - python
    - setuptools
    - markupsafe

test:
  imports:
    - jinja2

about:
  home: http://jinja.pocoo.org/
  license: BSD License
  summary: 'A small but fast and easy to use stand-alone template engine written in pure python.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
