package:
  name: pip
  version: "8.1.0"

source:
  fn: pip-8.1.0.tar.gz
  url: https://pypi.python.org/packages/source/p/pip/pip-8.1.0.tar.gz
  md5: e9c3844db343f47d16040b32ad9072be

build:
  number: 99
  entry_points:
    - pip=pip:main
    - pip2=pip:main    [py2k]
    - pip2.7=pip:main  [py27]

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - pip
    - pip._vendor
    - pip._vendor._markerlib
    - pip._vendor.cachecontrol
    - pip._vendor.cachecontrol.caches
    - pip._vendor.colorama
    - pip._vendor.distlib
    - pip._vendor.distlib._backport
    - pip._vendor.html5lib
    - pip._vendor.html5lib.filters
    - pip._vendor.html5lib.serializer
    - pip._vendor.html5lib.treeadapters
    - pip._vendor.html5lib.treebuilders
    - pip._vendor.html5lib.treewalkers
    - pip._vendor.html5lib.trie
    - pip._vendor.lockfile
    - pip._vendor.packaging
    - pip._vendor.pkg_resources
    - pip._vendor.progress
    - pip._vendor.requests
    - pip._vendor.requests.packages
    - pip._vendor.requests.packages.chardet
    - pip._vendor.requests.packages.urllib3
    - pip._vendor.requests.packages.urllib3.contrib
    - pip._vendor.requests.packages.urllib3.packages
    - pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname
    - pip._vendor.requests.packages.urllib3.util
    - pip.commands
    - pip.compat
    - pip.models
    - pip.operations
    - pip.req
    - pip.utils
    - pip.vcs

  commands:
    - pip --help
    - pip2 --help    [py2k]
    - pip2.7 --help  [py27]

about:
  home: https://pip.pypa.io/
  license: MIT License
  summary: 'The PyPA recommended tool for installing Python packages.'
