package:
  name: constructor
  version: 1.0.0

source:
  git_url: https://github.com/conda/constructor.git
  git_tag: 1.0.0

build:
  number: 0

requirements:
  build:
    - python
  run:
    - python
    - conda
    - pillow >=3.1      [win]
    - nsis              [win]

test:
  commands:
    - constructor --test
  imports:
    - constructor

about:
  home: https://github.com/conda/constructor
  license: BSD
  license_file: LICENSE.txt
  summary: tool which allows creating installers for conda packages
