package:
  name: pycosat
  version: "0.6.1"

source:
  fn: pycosat-0.6.1.tar.gz
  url: https://pypi.python.org/packages/source/p/pycosat/pycosat-0.6.1.tar.gz
  md5: c1fc35b17865f5f992595ae0362f9f9f
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pycosat = pycosat:main
    #
    # Would create an entry point called pycosat that calls pycosat.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/ContinuumIO/pycosat
  license: MIT
  summary: 'bindings to picosat (a SAT solver)'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
