package:
  name: openssl
  version: "1.0.2g"

source:
  fn: openssl-1.0.2g.tar.gz
  url: https://www.openssl.org/source/openssl-1.0.2g.tar.gz
  md5: f3c710c045cdee5fd114feb69feba7aa

build:
  number: 0

about:
  home: https://www.openssl.org
  license: Apache-style (http://www.openssl.org/source/license.html)
