package:
  name: requests
  version: "2.9.1"

source:
  fn: requests-2.9.1.tar.gz
  url: https://pypi.python.org/packages/source/r/requests/requests-2.9.1.tar.gz
  md5: 0b7f480d19012ec52bab78292efd976d

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - requests
    - requests.packages
    - requests.packages.chardet
    - requests.packages.urllib3
    - requests.packages.urllib3.contrib
    - requests.packages.urllib3.packages
    - requests.packages.urllib3.packages.ssl_match_hostname
    - requests.packages.urllib3.util

about:
  home: http://python-requests.org
  license: Apache Software License
  summary: 'Python HTTP for Humans.'
